version: "3"

volumes:
    keys:
    db-data:

services:

  web:
    container_name: wordpress_web
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/vhosts.conf:/etc/apache2/sites-available/000-default.conf
      - keys:/root/.ssh
    depends_on:
      - data
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  data:
    container_name: wordpress_data
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./docker/my.cnf:/root/.my.cnf
      - ./data:/var/www/html/data
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
